# Auto-generated by generate_height_filter_from_urdf.py
# Source mapping: /root/ros2_ws/src/height_map_ros2/config/autonomy.yaml
# Source URDF: /root/ros2_ws/src/height_map_ros2/urdf/f4.urdf
#
from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

import torch

from isaaclab.markers import VisualizationMarkers
from isaaclab.sensors.ray_caster import RayCaster


@dataclass
class RayCasterFOVData:
    """Data container for camera-FOV-mask ray caster."""

    pos_w: torch.Tensor = None
    """Sensor origin position in world frame. Shape: (N, 3)."""

    quat_w: torch.Tensor = None
    """Sensor origin orientation in world frame. Shape: (N, 4), convention: wxyz."""

    ray_hits_w: torch.Tensor = None
    """Original RayCaster ray hit positions in world frame. Shape: (N, B, 3)."""

    raw_ray_hits_w: torch.Tensor = None
    """Same as original ray_hits_w. Kept explicitly for GT visualization/custom obs."""

    valid_mask: torch.Tensor = None
    """Combined camera FOV valid mask. Shape: (N, B). 1.0 = visible, 0.0 = invisible."""

    per_camera_valid_masks: dict = None
    """Per-camera valid masks. Dict[str, Tensor[N, B]]."""


class RayCasterFOV(RayCaster):
    """RayCaster that computes camera-FOV masks from actual ray hit points.

    Important:
        This class does NOT modify ray_hits_w.

    It is intended for:
        1. GT raw height scanner visualization
        2. camera-FOV-filtered point visualization
        3. later obs masking through a custom observation function
    """

    def __init__(self, *args, **kwargs):
        # IsaacLab SensorBase.__init__() may call set_debug_vis() immediately
        # when cfg.debug_vis=True. Therefore all debug visualizer attributes
        # must exist before super().__init__().
        self.gt_visualizer = None
        self.combined_valid_visualizer = None
        self.invalid_visualizer = None
        self.per_camera_visualizers = {}

        self._height_map_w = None
        self._height_map_h = None
        self._warned_zero_valid = False

        super().__init__(*args, **kwargs)

        # Replace parent RayCaster data container after parent initialization.
        # Parent update logic writes to fields with the same names.
        self._data = RayCasterFOVData()

    def __str__(self) -> str:
        valid_count = int(self._data.valid_mask[0].sum().item()) if self._data.valid_mask is not None else 0
        total_count = int(self._data.valid_mask.shape[1]) if self._data.valid_mask is not None else 0

        return (
            f"RayCasterFOV @ '{self.cfg.prim_path}': \n"
            f"\tview type            : {self._view.__class__}\n"
            f"\tupdate period (s)    : {self.cfg.update_period}\n"
            f"\tnumber of meshes     : {len(self.meshes)}\n"
            f"\tnumber of sensors    : {self._view.count}\n"
            f"\tnumber of rays/sensor: {self.num_rays}\n"
            f"\ttotal number of rays : {self.num_rays * self._view.count}\n"
            f"\tFOV valid rays       : {valid_count} / {total_count}\n"
        )

    @property
    def data(self) -> RayCasterFOVData:
        self._update_outdated_buffers()
        return self._data

    def reset(self, env_ids: Sequence[int] | None = None):
        super().reset(env_ids)

        if env_ids is None:
            env_ids = slice(None)

        if self._data.raw_ray_hits_w is not None:
            self._data.raw_ray_hits_w[env_ids] = 0.0

        if self._data.valid_mask is not None:
            self._data.valid_mask[env_ids] = 0.0

        if self._data.per_camera_valid_masks is not None:
            for mask in self._data.per_camera_valid_masks.values():
                mask[env_ids] = 0.0

    def _initialize_impl(self):
        super()._initialize_impl()

        self._height_map_w = int(round(self.cfg.pattern_cfg.size[0] / self.cfg.pattern_cfg.resolution) + 1)
        self._height_map_h = int(round(self.cfg.pattern_cfg.size[1] / self.cfg.pattern_cfg.resolution) + 1)

        expected_num_rays = self._height_map_w * self._height_map_h
        if expected_num_rays != self.num_rays:
            raise RuntimeError(
                f"RayCasterFOV grid mismatch: pattern_cfg gives "
                f"{self._height_map_h}x{self._height_map_w}={expected_num_rays} rays, "
                f"but RayCaster has num_rays={self.num_rays}. "
                f"This implementation assumes GridPatternCfg."
            )

        self._data.raw_ray_hits_w = torch.zeros(
            self._view.count,
            self.num_rays,
            3,
            dtype=torch.float32,
            device=self._device,
        )

        self._data.valid_mask = torch.zeros(
            self._view.count,
            self.num_rays,
            dtype=torch.float32,
            device=self._device,
        )

        self._data.per_camera_valid_masks = {}
        for cam in self._camera_configs():
            self._data.per_camera_valid_masks[cam["role"]] = torch.zeros(
                self._view.count,
                self.num_rays,
                dtype=torch.float32,
                device=self._device,
            )

    def _camera_configs(self):
        cameras = self.cfg.cameras
        if isinstance(cameras, dict):
            return (cameras,)
        return cameras

    @staticmethod
    def _quat_apply(quat: torch.Tensor, vec: torch.Tensor) -> torch.Tensor:
        """Apply quaternion rotation to vector. Quaternion convention: w, x, y, z."""
        q_w = quat[..., 0:1]
        q_xyz = quat[..., 1:4]

        t = 2.0 * torch.cross(q_xyz, vec, dim=-1)
        return vec + q_w * t + torch.cross(q_xyz, t, dim=-1)

    @staticmethod
    def _quat_inv(quat: torch.Tensor) -> torch.Tensor:
        inv = quat.clone()
        inv[..., 1:4] *= -1.0
        return inv

    def _get_base_pose_from_sensor_pose(self, env_ids: Sequence[int]):
        """Return the base pose that RayCaster stored from cfg.prim_path.

        IsaacLab RayCaster applies cfg.offset.pos to ray_starts, not to data.pos_w.
        Since this sensor is attached to base_link, data.pos_w/data.quat_w already
        represent the base pose and must not subtract cfg.offset.pos again.
        """
        return self._data.pos_w[env_ids], self._data.quat_w[env_ids]

    def _world_hits_to_base(
        self,
        ray_hits_w: torch.Tensor,
        base_pos_w: torch.Tensor,
        base_quat_w: torch.Tensor,
    ) -> torch.Tensor:
        """Transform ray hit points from world frame to base-aligned frame."""
        rel_w = ray_hits_w - base_pos_w.unsqueeze(1)
        quat_inv = self._quat_inv(base_quat_w).unsqueeze(1)
        return self._quat_apply(quat_inv, rel_w)

    def _compute_fov_masks_from_hits(self, points_base: torch.Tensor):
        """Compute camera FOV masks from actual ray hit points.

        Args:
            points_base: Tensor shape [N, B, 3]

        Returns:
            combined_mask: Tensor shape [N, B], bool
            per_camera_masks: Dict[str, Tensor[N, B]], bool
        """
        num_envs, num_rays, _ = points_base.shape

        ones = torch.ones(
            num_envs,
            num_rays,
            1,
            device=self._device,
            dtype=torch.float32,
        )

        points_base_h = torch.cat([points_base, ones], dim=-1)

        combined = torch.zeros(
            num_envs,
            num_rays,
            device=self._device,
            dtype=torch.bool,
        )
        per_camera = {}

        for cam in self._camera_configs():
            T_base_optical = torch.tensor(
                cam["T_base_optical"],
                device=self._device,
                dtype=torch.float32,
            )

            T_optical_base = torch.linalg.inv(T_base_optical)

            # row-vector homogeneous transform
            points_optical = torch.matmul(points_base_h, T_optical_base.T)[..., :3]

            x = points_optical[..., 0]
            y = points_optical[..., 1]
            z = points_optical[..., 2]

            h_half = torch.deg2rad(
                torch.tensor(float(cam["h_fov_deg"]), device=self._device, dtype=torch.float32)
            ) * 0.5

            v_half = torch.deg2rad(
                torch.tensor(float(cam["v_fov_deg"]), device=self._device, dtype=torch.float32)
            ) * 0.5

            valid_depth = (z > float(cam["min_depth"])) & (z < float(cam["max_depth"]))
            valid_h = torch.abs(torch.atan2(x, z)) < h_half
            valid_v = torch.abs(torch.atan2(y, z)) < v_half

            mask = valid_depth & valid_h & valid_v

            per_camera[cam["role"]] = mask
            combined |= mask

        return combined, per_camera

    def _update_buffers_impl(self, env_ids: Sequence[int]):
        super()._update_buffers_impl(env_ids)

        # Keep original RayCaster result as GT.
        raw_hits = self._data.ray_hits_w[env_ids].clone()
        self._data.raw_ray_hits_w[env_ids] = raw_hits

        # Compute FOV mask using actual 3D hit points.
        base_pos_w, base_quat_w = self._get_base_pose_from_sensor_pose(env_ids)
        points_base = self._world_hits_to_base(raw_hits, base_pos_w, base_quat_w)

        combined_mask, per_camera_masks = self._compute_fov_masks_from_hits(points_base)

        self._data.valid_mask[env_ids] = combined_mask.to(dtype=torch.float32)

        for role, mask in per_camera_masks.items():
            self._data.per_camera_valid_masks[role][env_ids] = mask.to(dtype=torch.float32)

        if bool(self.cfg.debug_print_valid_counts):
            counts = combined_mask.sum(dim=1)
            if torch.any(counts > 0) or not self._warned_zero_valid:
                per_role_counts = {
                    role: mask.sum(dim=1).detach().cpu().tolist() for role, mask in per_camera_masks.items()
                }
                print(
                    "[RayCasterFOV] valid_counts="
                    f"{counts.detach().cpu().tolist()} per_camera={per_role_counts}"
                )
                self._warned_zero_valid = bool(torch.all(counts == 0))

        # IMPORTANT:
        # Do not modify self._data.ray_hits_w.
        # Observation masking should use data.valid_mask.

    def _set_debug_vis_impl(self, debug_vis: bool):
        # Extra guard for early SensorBase initialization.
        if not hasattr(self, "gt_visualizer"):
            self.gt_visualizer = None
        if not hasattr(self, "combined_valid_visualizer"):
            self.combined_valid_visualizer = None
        if not hasattr(self, "invalid_visualizer"):
            self.invalid_visualizer = None
        if not hasattr(self, "per_camera_visualizers"):
            self.per_camera_visualizers = {}

        if debug_vis:
            if self.gt_visualizer is None:
                self.gt_visualizer = VisualizationMarkers(self.cfg.gt_visualizer_cfg)
            if self.combined_valid_visualizer is None:
                self.combined_valid_visualizer = VisualizationMarkers(self.cfg.combined_valid_visualizer_cfg)
            if self.invalid_visualizer is None:
                self.invalid_visualizer = VisualizationMarkers(self.cfg.invalid_visualizer_cfg)

            if not self.per_camera_visualizers:
                for role, cfg in self.cfg.per_camera_visualizer_cfgs.items():
                    self.per_camera_visualizers[role] = VisualizationMarkers(cfg)

            self.gt_visualizer.set_visibility(bool(self.cfg.debug_show_gt))
            self.combined_valid_visualizer.set_visibility(bool(self.cfg.debug_show_combined_valid))
            self.invalid_visualizer.set_visibility(bool(self.cfg.debug_show_invalid))

            for role, visualizer in self.per_camera_visualizers.items():
                visualizer.set_visibility(bool(self.cfg.debug_show_per_camera))

        else:
            if self.gt_visualizer is not None:
                self.gt_visualizer.set_visibility(False)
            if self.combined_valid_visualizer is not None:
                self.combined_valid_visualizer.set_visibility(False)
            if self.invalid_visualizer is not None:
                self.invalid_visualizer.set_visibility(False)
            for visualizer in self.per_camera_visualizers.values():
                visualizer.set_visibility(False)

    @staticmethod
    def _visualize_or_hide(visualizer, points: torch.Tensor, visible: bool):
        if visualizer is None:
            return
        if not visible or points.numel() == 0:
            visualizer.set_visibility(False)
            return
        visualizer.set_visibility(True)
        visualizer.visualize(points.reshape(-1, 3))

    def _with_debug_z_offset(self, points: torch.Tensor, z_offset: float) -> torch.Tensor:
        if points.numel() == 0 or z_offset == 0.0:
            return points
        offset_points = points.clone()
        offset_points[..., 2] += float(z_offset)
        return offset_points

    def _debug_vis_callback(self, event):
        if self._data.ray_hits_w is None or self._data.valid_mask is None:
            return

        ray_hits_w = self._data.ray_hits_w

        self._visualize_or_hide(
            self.gt_visualizer,
            ray_hits_w,
            bool(self.cfg.debug_show_gt),
        )

        valid = self._data.valid_mask.bool()

        self._visualize_or_hide(
            self.combined_valid_visualizer,
            self._with_debug_z_offset(ray_hits_w[valid], self.cfg.debug_valid_z_offset),
            bool(self.cfg.debug_show_combined_valid),
        )

        if bool(self.cfg.debug_show_invalid):
            invalid = ~valid
            self._visualize_or_hide(
                self.invalid_visualizer,
                ray_hits_w[invalid],
                True,
            )
        elif self.invalid_visualizer is not None:
            self.invalid_visualizer.set_visibility(False)

        if bool(self.cfg.debug_show_per_camera):
            for role, mask_float in self._data.per_camera_valid_masks.items():
                if role not in self.per_camera_visualizers:
                    continue

                mask = mask_float.bool()
                self._visualize_or_hide(
                    self.per_camera_visualizers[role],
                    self._with_debug_z_offset(ray_hits_w[mask], self.cfg.debug_valid_z_offset),
                    True,
                )
        else:
            for visualizer in self.per_camera_visualizers.values():
                visualizer.set_visibility(False)
