# Auto-generated by generate_height_filter_from_urdf.py
# Source mapping: /root/ros2_ws/src/height_map_ros2/config/autonomy.yaml
# Source URDF: /root/ros2_ws/src/height_map_ros2/urdf/f4.urdf
#
from isaaclab.utils import configclass
from isaaclab.markers import VisualizationMarkersCfg
import isaaclab.sim as sim_utils
from isaaclab.sensors import RayCasterCfg

from .ray_caster_fov import RayCasterFOV


GT_MARKER_CFG = VisualizationMarkersCfg(
    prim_path="/Visuals/RayCasterFOV/GT",
    markers={
        "hit": sim_utils.SphereCfg(
            radius=0.008,
            visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.12, 0.12, 0.12)),
        ),
    },
)

COMBINED_VALID_MARKER_CFG = VisualizationMarkersCfg(
    prim_path="/Visuals/RayCasterFOV/CombinedValid",
    markers={
        "hit": sim_utils.SphereCfg(
            radius=0.035,
            visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.0, 1.0, 0.0)),
        ),
    },
)

INVALID_MARKER_CFG = VisualizationMarkersCfg(
    prim_path="/Visuals/RayCasterFOV/Invalid",
    markers={
        "hit": sim_utils.SphereCfg(
            radius=0.016,
            visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(1.0, 0.0, 0.0)),
        ),
    },
)


PER_CAMERA_MARKER_CFGS = {
    "adas": VisualizationMarkersCfg(
        prim_path="/Visuals/RayCasterFOV/adas",
        markers={
            "hit": sim_utils.SphereCfg(
                radius=0.028,
                visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.0, 0.4, 1.0)),
            ),
        },
    ),
    "front": VisualizationMarkersCfg(
        prim_path="/Visuals/RayCasterFOV/front",
        markers={
            "hit": sim_utils.SphereCfg(
                radius=0.028,
                visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(1.0, 0.7, 0.0)),
            ),
        },
    ),
}


CAMERA_FOV_DATA = (
    {
        "role": "adas",
        "model": "D435",
        "mount_frame": "A_camera_mount_link",
        "optical_frame": "A_camera_link",
        "h_fov_deg": 87.0000000000,
        "v_fov_deg": 58.0000000000,
        "min_depth": 0.1000000000,
        "max_depth": 2.5000000000,
        "T_base_optical": ((-0.0000000000, -0.0000000000, 1.0000000000, 0.2400000000), (-1.0000000000, 0.0000000000, -0.0000000000, 0.0000000000), (0.0000000000, -1.0000000000, -0.0000000000, 0.1200000000), (0.0000000000, 0.0000000000, 0.0000000000, 1.0000000000)),
    },
    {
        "role": "front",
        "model": "D435",
        "mount_frame": "F_camera_link",
        "optical_frame": "F_camera_link",
        "h_fov_deg": 87.0000000000,
        "v_fov_deg": 58.0000000000,
        "min_depth": 0.1000000000,
        "max_depth": 2.5000000000,
        "T_base_optical": ((-0.0033087169, -0.7070990400, 0.7071067812, 0.2118583431), (-0.9999890523, 0.0046792323, -0.0000000000, 0.0006329723), (-0.0033087169, -0.7070990400, -0.7071067812, -0.0842872753), (0.0000000000, 0.0000000000, 0.0000000000, 1.0000000000)),
    },
)


HEIGHT_MAP_PATTERN = {"resolution": 0.05, "size": (1.55, 1.05), "offset": (0, 0), "ros_width": 32, "ros_height": 22}
LOCAL_HEIGHT_MAP_PATTERN = {"resolution": 0.05, "size": (2.75, 1.45), "offset": (0.6, 0), "ros_width": 56, "ros_height": 30}


@configclass
class RayCasterFOVCfg(RayCasterCfg):
    """RayCaster config with URDF+camera-FOV mask.

    This sensor does not modify ray_hits_w.
    It computes:
      - raw_ray_hits_w
      - valid_mask
      - per_camera_valid_masks

    Debug visualization:
      - GT gray points: original height scanner grid
      - combined valid green points: any camera can see
      - per-camera colored points: each camera's FOV result
      - invalid red points: optional, usually noisy because it shows the full remaining rectangle
    """

    class_type: type = RayCasterFOV

    gt_visualizer_cfg: VisualizationMarkersCfg = GT_MARKER_CFG
    combined_valid_visualizer_cfg: VisualizationMarkersCfg = COMBINED_VALID_MARKER_CFG
    invalid_visualizer_cfg: VisualizationMarkersCfg = INVALID_MARKER_CFG
    per_camera_visualizer_cfgs: dict = PER_CAMERA_MARKER_CFGS

    cameras: tuple = CAMERA_FOV_DATA

    # 전체 기존 height scanner GT를 회색으로 표시.
    debug_show_gt: bool = True

    # 모든 카메라를 합친 valid 영역을 초록색으로 표시.
    # per-camera와 겹쳐 보이면 False로 꺼도 됨.
    debug_show_combined_valid: bool = True

    # 카메라별 FOV 영역을 색상별로 표시.
    debug_show_per_camera: bool = False

    # FOV 밖 점을 빨간색으로 표시.
    # 전체 사각형이 많이 보이므로 필요할 때만 True.
    debug_show_invalid: bool = False

    # FOV 점을 GT 점보다 살짝 위에 그려 viewport에서 가려지지 않게 한다.
    debug_valid_z_offset: float = 0.03

    # True면 valid ray 개수를 콘솔에 출력해서 FOV 계산 상태를 확인한다.
    debug_print_valid_counts: bool = False
